// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // GoogleService-Info.plistから以下の値を入力してください
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXhIYNUHXx29wzJdDIeDqoZG4w6QDq_FU', // iOSのAPIキー
    appId: '1:757279698129:ios:80c99c58d7c53a137169f0', // iOSのApp ID
    messagingSenderId: '757279698129',
    projectId: 'reflekt-journal-a436b',
    storageBucket: 'reflekt-journal-a436b.appspot.com',
    iosBundleId: 'com.kenzosasaki.reflekt.reflektApp', // あなたのバンドルID
  );

  // google-services.jsonから以下の値を入力してください
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDihYafE-5bed2QqvjSCKNQ9XVhEI70g2o',
    appId: '1:757279698129:android:bf02ee56e7d059137169f0',
    messagingSenderId: '757279698129',
    projectId: 'reflekt-journal-a436b',
    storageBucket: 'reflekt-journal-a436b.appspot.com',
  );

  // Webの設定（必要な場合）
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDihYafE-5bed2QqvjSCKNQ9XVhEI70g2o',
    appId: '1:757279698129:web:e4efba1df48a17ce7169f0',
    messagingSenderId: '757279698129',
    projectId: 'reflekt-journal-a436b',
    storageBucket: 'reflekt-journal-a436b.appspot.com',
    authDomain: 'reflekt-journal-a436b.firebaseapp.com',
  );
}
